name: Continious Deployment
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: docker build . -t freekvanlier-website-build
      - run: docker run -d -p 8080:80 --name freekvanlier-website freekvanlier-website-build